---
date: 2023-02-13
date-format: "YYYY/MM/DD"
format: docx
---

氏名：山口敏弘

# 職務経歴書

## 職務要約

過去５年間主にデータサイエンティストとして働くなかで、様々な課題に対しその場で適切なアプローチを検討・実践してきました。

現在はコンサルティング会社で働いており、課題整理や資料作成といったコンサルタントとしてのスキルを学びつつ、
データサイエンスを KPI と紐付けて事業を改善する方法について学んでおります。

これまで働いた様々な現場で共通する問題点として、

- データサイエンスの知見をとシステム開発に結びつける際に非常に多くの時間や労力がかかる
- レビューなどが行われていないため、分析タスクがデータサイエンティストに俗人化しており、分析の改善などがしにくい状況にある
  といったものがあります。

私自身、この点で苦労した経験があるためこれまでの経験やスキルを活かして貢献できないかと思っています。

日々データ分析や MLOps について学んでいますので、もし同じような考えをお持ちの方がいらっしゃいましたら一緒に働かせて頂きたいです。

## スキル

- 機械学習（DL/NLP/Image Recognition）・統計学・因果推論
- 機械学習システムの設計・構築
- 機械学習システムの継続的な改善
- インフラ、サーバーサイド、フロントエンドを含めた Web アプリケーションの開発の経験

## 開発環境/言語/ライブラリ

- GCP AWS Databricks
- Python R
- Pyspark Pandas scikit-learn TensorFlow PyTorch MLFlow

## 資格

- ネットワークスペシャリスト
- 情報セキュリティ安全確保支援士試験合格
- Google Cloud Professional Data Engineer
- Google Cloud Professional Machine Learning Engineer

## イベント

- MLOps 勉強会登壇(https://mlops.connpass.com/event/218772/
- AWS Dev Day 登壇(https://www.databricks.com/p/webinar/aws-dev-days-jp)

## 職務経歴

### EY ストラテジーアンドコンサルティング (2022/09/01 -)

- M＆A データの分析

  - 期間: 2023/01/01 -
  - 概要: M＆A を担当する部署の投資先企業探索をサポートするため、推薦システムを作成
  - 担当: フロントエンド開発　アルゴリズム開発
  - 環境・手法: Python VBA FastAPI
  - プロジェクト人数: 5

- 中古車ディーラーが販売先の中進国に与える経済効果を算出

  - 期間: 2022/12/01 - 2022/01/31
  - 概要: 中古車ディーラーが販売先の中進国に与える経済効果を貿易データや国勢調査データを利用して算出
  - 担当: データエンジニア　データサイエンティスト
  - 環境・手法: 課題整理・プレゼン資料作成・統計的因果推論
  - プロジェクト人数: 7

- 財務モデル作成

  - 期間: 2022/12/01 - 2023/01/31
  - 概要: EV を算出する財務モデルを作成
  - 担当: バックエンド開発,フロントエンド開発
  - 環境・手法: Excel VBA
  - プロジェクト人数: 7

### 株式会社日本経済通信社（嘱託契約　期間 3 年　 2019/08/01 - 2022/07/31）

- データ分析基盤の設計・構築

  - 期間: 2019/10/01 - 2022/07/31
  - 概要: Databricks と協力し、日経アプリのパーソナライズ機能に利用するデータ分析基盤をの設計と構築を行う
  - 担当: データ基盤設計・データ基盤構築
  - 環境・手法: Databricks AWS GCP
  - プロジェクト人数: 7

- 推薦アルゴリズム開発

  - 期間: 2020/02/01 - 2022/07/31
  - 概要: 日経アプリのパーソナライズ機能のアルゴリズム開発
  - 担当: アルゴリズム開発
  - 環境・手法: Jupyter Notebook, TensorFlow, Pytorch, BERT,協調フィルタリング
  - プロジェクト人数:

- 機械学習システム運用

  - 期間: 2020/06/01 - 2022/07/31
  - 概要: 推薦システムの機械学習運用の自動化や A/B テストによる効果検証などを行う
  - 担当: アーキテクチャ設計,クラウド開発,バックエンド開発
  - 環境・手法: AWS,Databricks,GCP A/B テスト,CI/CD
  - プロジェクト人数: 7

### 株式会社 aiforce solutions（2019/02/01 - 2019/07/31）

- スーパーマーケットの購買傾向の分析

  - 期間: 2019/04/01 - 2019/07/31
  - 概要: 大手商社の DX 事業部に常駐し、AI 活用に関 する相談を各事業部、子会社から受ける
  - 担当: データサイエンティスト
  - 環境・手法: R, アソシエーション分析
  - プロジェクト人数: 3

- AI 学習プラットフォームを開発

  - 期間: 2019/02/01 - 2019/07/31
  - 概要: AI 教育用のプラットフォーム開発
  - 担当: バックエンド開発,フロントエンド開発
  - 環境・手法: AWS,Bottle,Python,React
  - プロジェクト人数: 5

### 株式会社グリッド（2017/04/01 - 2019/01/31）

- DL ライブラリの画像モジュールの論文調査と学習

  - 期間: 2018/01/01 - 2019/01/31
  - 概要: 自社制作の DL ライブラリの画像モジュールを担当
  - 担当: チームリーダー,機械学習エンジニア
  - 環境・手法: Python, SSG,VAE,VGG
  - プロジェクト人数: 5

- 画像認識システム開発の FE/BE 開発

  - 期間: 2018/01/01 - 2019/01/31
  - 概要:
  - 担当:
  - 環境・手法:
  - プロジェクト人数:

- プラント制御の強化学習基盤

  - 期間: 2018/11/01 - 2019/01/31
  - 概要: 強化学習によるプラント制御 PJ のインフラを担当
  - 担当: データエンジニア,データ基盤設計
  - 環境・手法: Python, MQTT
  - プロジェクト人数: 3

- Fax 画像の分類モデル

  - 期間: 2017/04/01 - 2018/12/31
  - 概要: Fax 画像の分類モデルの作成及び、業務システムへの組み込み
  - 担当: データサイエンティスト
  - 環境・手法: OpenCV,Python, VAE,VGG
  - プロジェクト人数: 2

### 株式会社 Cuon（2016/01/01 - 2017/03/31）

- 社内ポータルサイト作成

  - 期間: 2016/12/01 - 2017/03/31
  - 概要: サービスサイトの設計・構築及び PM を担当
  - 担当: データサイエンティスト
  - 環境・手法: OpenCV,Python, VGG
  - プロジェクト人数: 2

### 株式会社 AP コミュニケーションズ（2014/03/01 - 2015/12/31）

- 社内インフラの運用・保守

  - 期間: 2014/03/01 - 2015/12/31
  - 概要: 社内インフラの運用・保守
  - 担当: 運用・保守
  - 環境・手法: Windows Server
  - プロジェクト人数: 15

- 社内インフラの運用設計作成

  - 期間: 2015/06/01 - 2015/12/31
  - 概要: 社内インフラの運用設計作成
  - 担当: 設計
  - 環境・手法: ITIL
  - プロジェクト人数: 15

### 日本通信株式会社（2013/04/01 - 2014/04/30）

- 自社サービスサイトの設計・構築

  - 期間: 2013/04/01 2014/04/30
  - 概要: 自社サイトのサービスサイトを LAMP 構成で作成した
  - 担当: 設計,構築
  - 環境・手法: Apache,Linux,MySQL,PHP
  - プロジェクト人数: 2
