project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "Blog"
  site-url: https://blog.spin-glass.dev/
  description: "ポートフォリオと経歴に関する技術記事"
  favicon: favicon.ico
  open-graph: true
  twitter-card: true
  navbar:
    background: "#2c3e50"
    foreground: light
    left:
      - text: Resume
        href: https://resume-blond-nu.vercel.app/
      - text: Work
        href: https://resume-blond-nu.vercel.app/portfolio
    right:
      - icon: github
        href: https://github.com/spin-glass/resume
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/toshihiro-yamaguchi/
        aria-label: LinkedIn
  google-analytics:
    tracking-id: GTM-N9X6ZMF
    anonymize-ip: true

format:
  html:
    theme:
      - flatly
      - custom.scss
    toc: true
    toc-title: 目次
    toc-location: right
    code-fold: show
    lang: ja

