name: Convert Quarto to MDX

on:
  push:
    branches:
      - main  # または、使用しているブランチ名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tinytex: true

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: scheme-basic

    - name: Install Japanese Fonts
      run: |
        tlmgr install collection-langjapanese
        tlmgr install haranoaji

    - name: Render Quarto to PDF
      run: |
        quarto render public/assets/test.qmd
        # quarto render public/assets/resume-ja.qmd

    - name: Convert Quarto to MDX
      run: |
        python scripts/convert_quarto_to_mdx.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Convert Quarto to MDX'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
